// <auto-generated />
using System;
using HTTPApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HTTPApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210913043653_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HTTPApi.Model.PaymentListModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UsersModelid")
                        .HasColumnType("int");

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UsersModelid");

                    b.ToTable("tblPayment");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = "1500.00",
                            date = "9/1/2021",
                            status = "OK",
                            userid = 1
                        },
                        new
                        {
                            id = 2,
                            amount = "2500.00",
                            date = "9/2/2021",
                            status = "OK",
                            userid = 1
                        },
                        new
                        {
                            id = 3,
                            amount = "3500.00",
                            date = "9/3/2021",
                            status = "OK",
                            userid = 1
                        },
                        new
                        {
                            id = 4,
                            amount = "5460.00",
                            date = "8/24/2021",
                            status = "CLOSED",
                            userid = 2
                        },
                        new
                        {
                            id = 5,
                            amount = "600.00",
                            date = "7/1/2021",
                            status = "OK",
                            userid = 2
                        });
                });

            modelBuilder.Entity("HTTPApi.Model.UsersModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accountBalance")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblUser");

                    b.HasData(
                        new
                        {
                            id = 1,
                            accountBalance = "30000.00"
                        },
                        new
                        {
                            id = 2,
                            accountBalance = "50000.00"
                        });
                });

            modelBuilder.Entity("HTTPApi.Model.PaymentListModel", b =>
                {
                    b.HasOne("HTTPApi.Model.UsersModel", null)
                        .WithMany("paymentList")
                        .HasForeignKey("UsersModelid");
                });

            modelBuilder.Entity("HTTPApi.Model.UsersModel", b =>
                {
                    b.Navigation("paymentList");
                });
#pragma warning restore 612, 618
        }
    }
}
